TALLER_SCIACA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path, include
from . import views
from orden.urls import orden_patterns

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('ordenes/', include(orden_patterns)),
]

orden/urls.py
from django.urls import path
from .views import OrdenCreate, OrdenListView, OrdenDetailView, OrdenDeleteView

orden_patterns = ([
    path('', OrdenListView.as_view(), name='ordenes'),
    path('<int:id>/', OrdenDetailView.as_view(), name='detail'),
    path('<int:id>/delete', OrdenDeleteView.as_view(), name='delete'),
    # path('<int:id>/general/1', OrdenGeneralForm, name='general-form'),
    path('create/', OrdenCreate.as_view(), name='create'),
], 'orden')

orden/models.py
from django.db import models

class Orden(models.Model):
    MODALIDAD_CHOICES = [
        ('particular', 'Particular'),
        ('terceros', 'Contra terceros'),
        ('riesgo', 'Contra todo riesgo'),
        ('recupero', 'Recupero de siniestro')
    ]
    ESTADOS_CHOICES = [
        ('particular_uno', 'Enviar presupuesto a cliente'),
        ('particular_dos', 'Cobrar seña y asignar cita'),
        ('particular_tres', 'Cobrar primera mitad (descontando seña)'),
        ('particular_cuatro', 'Ingresar el auto al taller y realizar los trabajos correspondientes'),
        ('particular_cinco', 'Coordinar fecha de retiro con el dueño'),
        ('particular_seis', 'Cobrar segunda mitad'),
        ('terceros_uno', 'Primer paso de terceros'),
        ('riesgo_uno', 'Primer paso de riesgo'),
        ('recupero_uno', 'Primer paso de recupero'),
    ]

    nombre_cliente = models.CharField(max_length=200, verbose_name='Nombre del cliente', blank=False)
    telefono_cliente = models.CharField(max_length=200, verbose_name='Telefono del cliente', blank=False)
    marca_vehiculo = models.CharField(max_length=200, verbose_name='Marca del vehiculo', blank=False)
    modelo_vehiculo = models.CharField(max_length=200, verbose_name='Modelo del vehiculo', blank=False)
    patente_vehiculo = models.CharField(max_length=200, verbose_name='Patente del vehiculo', blank=False)
    imagenes = models.ImageField(upload_to='Imagenes/', verbose_name='Imagenes del vehiculo', blank=True, null=True)
    modalidad = models.CharField(max_length=50, choices=MODALIDAD_CHOICES, verbose_name='Modalidad de cobertura', blank=False)
    estado = models.CharField(max_length=50, choices=ESTADOS_CHOICES, verbose_name='Estado', blank=True)
    trabajos_a_realizar = models.TextField(verbose_name="Trabajos a realizar")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'orden'
        verbose_name_plural = 'ordenes'

    def __str__(self):
        return (self.marca_vehiculo + ' ' + self.modelo_vehiculo + ' de ' + self.nombre_cliente)

orden/forms.py
from django import forms
from .models import Orden


class OrdenForm(forms.ModelForm):
    class Meta:
        model = Orden
        fields = ['nombre_cliente', 'telefono_cliente', 'marca_vehiculo', 'modelo_vehiculo', 'patente_vehiculo', 'imagenes', 'modalidad', 'trabajos_a_realizar']
        widgets = {
            'nombre_cliente': forms.TextInput(attrs={'class': 'input-container-input', 'id': 'nombre_cliente'}),
            'telefono_cliente': forms.TextInput(attrs={'class': 'input-container-input', 'id': 'telefono_cliente'}),
            'marca_vehiculo': forms.TextInput(attrs={'class': 'input-container-input', 'id': 'marca_vehiculo'}),
            'modelo_vehiculo': forms.TextInput(attrs={'class': 'input-container-input', 'id': 'modelo_vehiculo'}),
            'patente_vehiculo': forms.TextInput(attrs={'class': 'input-container-input', 'id': 'patente_vehiculo'}),
            'imagenes': forms.ClearableFileInput(attrs={'class': 'input-container-input', 'id': ''}),
            'modalidad': forms.Select(attrs={'class': 'input-container-input', 'id': 'modalidad'}),
            'trabajos_a_realizar': forms.Textarea(attrs={'class': 'input-container-input', 'id': 'trabajos'})
        }

core/views.py
from django.shortcuts import render

# Create your views here.
def dashboard(request):
    return render(request, 'core/dashboard.html')
def clientes(request):
    return render(request, 'core/clientes.html')
def estadisticas(request):
    return render(request, 'core/estadisticas.html')
def notificaciones(request):
    return render(request, 'core/notificaciones.html')
def ajustes(request):
    return render(request, 'core/ajustes.html')

orden/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Orden
from .forms import OrdenForm

# Create your views here.
class OrdenListView(ListView):
    model = Orden
    context_object_name = 'ordenes'

class OrdenCreate(CreateView):
    model = Orden
    form_class = OrdenForm
    success_url = reverse_lazy('orden:ordenes')

    def form_valid(self, form):
        form.instance.estado = 'particular_uno'
        return super().form_valid(form)
    

    def form_invalid(self, form):
        print("Errores en el formulario:", form.errors)  # Debug en consola
        return super().form_invalid(form)

class OrdenDetailView(DetailView):
    model = Orden
    context_object_name = 'orden'

    def get_object(self):
        # Modifica para que busque la orden por id
        return get_object_or_404(Orden, id=self.kwargs['id'])
    
    

class OrdenDeleteView(DeleteView):
    model = Orden
    success_url = reverse_lazy('orden:ordenes')

    def get_object(self, queryset=None):
        return self.model.objects.get(id=self.kwargs['id'])  # Buscar por 'id'
    

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <!-- Material icon -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    
    <!-- Stylesheets -->
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    {% block stylesheets %}{% endblock stylesheets %}
</head>
<body>
    <div class="container">
    <aside>
        <div class="top">
            <div class="logo">
                <img src="/images/logo.png" alt="Logo">
                <h2 class="primary">
                    SC<span class="text-muted">IACA</span>
                </h2>
            </div>
            <div class="close" id="close-btn">
                <span class="material-symbols-outlined">close</span> 
            </div>
        </div>


        <div class="sidebar">
            <a href="{% url 'dashboard' %}" class="{% if request.path == '/' %}active{% endif %}">
                <span class="material-symbols-outlined">grid_view</span> 
                <h3>Dashboard</h3>
            </a>
            {% comment %} <a href="{% url 'cliente:clientes' %}" class="{% if '/clientes/' in request.path %}active{% endif %}">
                <span class="material-symbols-outlined">person_outline</span> 
                <h3>Clientes</h3>
            </a> {% endcomment %}
            <a href="{% url 'orden:ordenes' %}" class="{% if '/ordenes/' in request.path %}active{% endif %}">
                <span class="material-symbols-outlined">directions_car</span> 
                <h3>Ordenes</h3>
            </a>
            <a href="#">
                <span class="material-symbols-outlined">insights</span> 
                <h3>Estadisticas</h3>
            </a>
            <a href="#">
                <span class="material-symbols-outlined">mail_outline</span> 
                <h3>Notificaciones</h3>
                <span class="message-count">26</span>
            </a>
            <a href="#">
                <span class="material-symbols-outlined">settings</span>
                <h3>Settings</h3>
            </a>
            <a href="#">
                <span class="material-symbols-outlined">logout</span>
                <h3>Logout</h3>
            </a>
        </div>
    </aside>
    {% block content %}
        
    {% endblock %}
    <div class="right">
        <div class="top">
            <button id="menu-btn">
                <span class="material-symbols-outlined">menu</span>
            </button>
            <div class="theme-toggler" id="theme-toggler">
                <span class="material-symbols-outlined active">light_mode</span>
                <span class="material-symbols-outlined">dark_mode</span>
            </div>
            <div class="profile">
                <div class="info">
                    <p>Hey, <b>Daniel</b></p>
                    <small class="text-muted">Admin</small>
                </div>
                <div class="profile-photo">
                    <img src="/images/profile-1.jpg" alt="">
                </div>
            </div>
        </div>
        <!-- Finaliza parte superior -->

        <div class="recent-updates">
            <h2>Recent updates</h2>
            <div class="updates">
                <div class="update">
                    <div class="profile-photo">
                        <img src="images/profile-2.jpg" alt="">
                    </div>
                    <div class="message">
                        <p><b>Mike Tyson</b> received his order of Night Lion tech GPS drone</p>
                        <small class="text-muted"2 Minutes Ago></small>
                    </div>
                </div>
                <div class="update">
                    <div class="profile-photo">
                        <img src="images/profile-3.jpg" alt="">
                    </div>
                    <div class="message">
                        <p><b>Mike Tyson</b> received his order of Night Lion tech GPS drone</p>
                        <small class="text-muted"2 Minutes Ago></small>
                    </div>
                </div>
                <div class="update">
                    <div class="profile-photo">
                        <img src="images/profile-4.jpg" alt="">
                    </div>
                    <div class="message">
                        <p><b>Mike Tyson</b> received his order of Night Lion tech GPS drone</p>
                        <small class="text-muted"2 Minutes Ago></small>
                    </div>
                </div>
            </div>
        </div>
        <!-- Finaliza recent updates -->
         <div class="sales-analytics">
            <h2>Sales Analytics</h2>
            <div class="item online">
                <div class="icon">
                    <span class="material-symbols-outlined">shopping_cart</span>
                </div>
                <div class="right">
                    <div class="info">
                        <h3>ONLINE ORDERS</h3>
                        <small class="text-muted">Last 24 Hours</small>
                    </div>
                    <h5 class="success">+39%</h5>
                    <h3>3849</h3>
                </div>
            </div>
            <div class="item offline">
                <div class="icon">
                    <span class="material-symbols-outlined">local_mall</span>
                </div>
                <div class="right">
                    <div class="info">
                        <h3>OFFLINE ORDERS</h3>
                        <small class="text-muted">Last 24 Hours</small>
                    </div>
                    <h5 class="danger">-17%</h5>
                    <h3>1100</h3>
                </div>
            </div>
            <div class="item customers">
                <div class="icon">
                    <span class="material-symbols-outlined">person</span>
                </div>
                <div class="right">
                    <div class="info">
                        <h3>NEW CUSTOMERS</h3>
                        <small class="text-muted">Last 24 Hours</small>
                    </div>
                    <h5 class="success">+25%</h5>
                    <h3>849</h3>
                </div>
            </div>
            <div class="item add-product">
                <div>
                    <span class="material-symbols-outlined">add</span>
                    <h3>Add Product</h3>
                </div>
            </div>
         </div>
    </div>

    </div>

    
    
    <script src="{% static 'core/index.js' %}"></script>
</body>
</html>

core/templates/core/dashboard.html
{% extends 'core/base.html' %}

{% block content %}
    
    
    <!-- Finaliza aside -->
    <main>
        <h1>Dashboard</h1>
        <div class="insights">
            <div class="sales">
                <span class="material-symbols-outlined">analytics</span>
                <div class="middle">
                    <div class="left">
                        <h3>Total Sales</h3>
                        <h1>$25,024</h1>
                    </div>
                    <div class="progress">
                        <svg>
                            <circle cx="38" cy="38" r="36"></circle>
                        </svg>
                        <div class="number">
                            <p>81%</p>
                        </div>
                    </div>
                </div>
                <small class="text-muted">Last 24 hours</small>
            </div>
            <!-- Finaliza Ventas -->

            <div class="expenses">
                <span class="material-symbols-outlined">bar_chart</span>
                <div class="middle">
                    <div class="left">
                        <h3>Total Expenses</h3>
                        <h1>$14,160</h1>
                    </div>
                    <div class="progress">
                        <svg>
                            <circle cx="38" cy="38" r="36"></circle>
                        </svg>
                        <div class="number">
                            <p>62%</p>
                        </div>
                    </div>
                </div>
                <small class="text-muted">Last 24 hours</small>
            </div>
            <!-- Finaliza Gastos -->

            <div class="income">
                <span class="material-symbols-outlined">stacked_line_chart</span>
                <div class="middle">
                    <div class="left">
                        <h3>Total Income</h3>
                        <h1>$10,864</h1>
                    </div>
                    <div class="progress">
                        <svg>
                            <circle cx="38" cy="38" r="36"></circle>
                        </svg>
                        <div class="number">
                            <p>44%</p>
                        </div>
                    </div>
                </div>
                <small class="text-muted">Last 24 hours</small>
            </div>
            <!-- Finaliza Ingresos -->
        </div>
        <!-- Finaliza Insights -->
         <div class="recent-orders">
            <h2>Recent Orders</h2>
            <table>
                <thead>
                    <tr>
                        <th>Product Name</th>
                        <th>Product Number</th>
                        <th>Payment</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Foldable Mini Drone</td>
                        <td>85631</td>
                        <td>Due</td>
                        <td class="warning">Pending</td>
                        <td class="primary">Details</td>
                    </tr>
                    <tr>
                        <td>Foldable Mini Drone</td>
                        <td>85631</td>
                        <td>Due</td>
                        <td class="warning">Pending</td>
                        <td class="primary">Details</td>
                    </tr>
                    <tr>
                        <td>Foldable Mini Drone</td>
                        <td>85631</td>
                        <td>Due</td>
                        <td class="warning">Pending</td>
                        <td class="primary">Details</td>
                    </tr>
                    <tr>
                        <td>Foldable Mini Drone</td>
                        <td>85631</td>
                        <td>Due</td>
                        <td class="warning">Pending</td>
                        <td class="primary">Details</td>
                    </tr>
                    <tr>
                        <td>Foldable Mini Drone</td>
                        <td>85631</td>
                        <td>Due</td>
                        <td class="warning">Pending</td>
                        <td class="primary">Details</td>
                    </tr>
                    <tr>
                        <td>Foldable Mini Drone</td>
                        <td>85631</td>
                        <td>Due</td>
                        <td class="warning">Pending</td>
                        <td class="primary">Details</td>
                    </tr>
                    <tr>
                        <td>Foldable Mini Drone</td>
                        <td>85631</td>
                        <td>Due</td>
                        <td class="warning">Pending</td>
                        <td class="primary">Details</td>
                    </tr>
                </tbody>
            </table>
            <a href="#">Show All</a>
         </div>
    </main>
    <!-- Finaliza Main -->

    


{% endblock content %}

orden/templates/orden/orden_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static "orden/css/orden-detail.css" %}">
{% endblock stylesheets %}

{% block content %}
<div class="orden-detail">
    <h1>Orden de {{orden.nombre_cliente}}</h1>
    <h2>Datos de la orden</h2>
    <ul>
        <li>Nombre: {{orden.nombre_cliente}}</li>
        <li>Telefono: {{orden.telefono_cliente}}</li>
        <li>Marca: {{orden.marca_vehiculo}}</li>
        <li>Modelo: {{orden.modelo_vehiculo}}</li>
        <li>Patente: {{orden.patente_vehiculo}}</li>
        <li>Cobertura: {{orden.modalidad}}</li>
        <li>Creado: {{orden.created}}</li>
        <li>Imagenes: {{orden.imagenes}}</li>
        <li>Trabajos a realizar: {{orden.trabajos_a_realizar}}</li>
    </ul>
    <h3>Proximos pasos</h3>
    <ul>
        {% for paso in siguientesPasos %}
            <li>{{paso}}</li>
        {% endfor %}
        
    </ul>

    <form action="{% url 'orden:delete' id=orden.id %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn-delete">Eliminar Orden</button>
    </form>
</div>
{% endblock content %}

orden/templates/orden/orden_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static "orden/css/orden-form.css" %}">
{% endblock stylesheets %}

{% block content %}
<div>
    <div class="datos-orden" enctype="multipart/form-data">
        <h1>Nueva Orden</h1>
        <form method="post">
            {% csrf_token %}
            <div class="datos-cliente"> 
                <h2>Datos del cliente</h2>
                <div class="inputs">
                    <div class="input-container">
                        <label for="nombre_cliente" class="input-container-label">Nombre del cliente</label>
                        {{ form.nombre_cliente }}
                    </div>
                    <div class="input-container">
                        <label for="telefono_cliente" class="input-container-label">Telefono del cliente</label>
                        {{ form.telefono_cliente }}
                    </div>
                </div>
            </div>
            <div class="datos-vehiculo">
                <h2>Datos del vehiculo</h2>
                <div class="inputs">
                    <div class="input-container">
                        <label for="marca_vehiculo" class="input-container-label">Marca del vehiculo</label>
                        {{ form.marca_vehiculo }}
                    </div>
                    <div class="input-container">
                        <label for="modelo_vehiculo" class="input-container-label">Modelo del vehiculo</label>
                        {{ form.modelo_vehiculo }}
                    </div>
                    <div class="input-container">
                        <label for="patente_vehiculo" class="input-container-label">Patente del vehiculo</label>
                        {{ form.patente_vehiculo }}
                    </div>
                    <div class="input-container">
                        <label for="modalidad" class="input-container-label">Modalidad de cobertura</label>
                        {{ form.modalidad }}
                    </div>
                    <div class="input-container">
                        <label for="imagenes" class="input-container-label">Imagenes del vehiculo</label>
                        {{ form.imagenes }}
                    </div>
                </div>
            </div>
            <div class='trabajos-vehiculo'>
                <label for="trabajos" class="input-container-label">Daños y trabajos a realizar al vehiculo</label>
                {{form.trabajos_a_realizar}}
            </div>
            <button type="submit">Enviar</button>
        </form> 
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("agregar-fila").addEventListener("click", function () {
            let container = document.getElementById("trabajos-container");
            let nuevaFila = document.createElement("div");
            nuevaFila.classList.add("trabajo-row");
            nuevaFila.innerHTML = `
                <select name="tipo-trabajo" class="tipo-trabajo">
                    <option value="">Seleccione tipo de trabajo</option>
                    <option value="Reparacion y pintura">Reparación y pintura</option>
                    <option value="Sustitucion">Sustitución</option>
                    <option value="Difuminado">Difuminado</option>
                </select>
                <select name="parte-vehiculo" class="parte-vehiculo">
                    <option value="">Seleccione parte del vehículo</option>
                    <option value="Guardabarros delantero derecho">Guardabarros delantero derecho</option>
                    <option value="Capot">Capot</option>
                    <option value="Paragolpes delantero">Paragolpes delantero</option>
                </select>
            `;
            container.appendChild(nuevaFila);
        });
    });
    </script>
{% endblock content %}

orden/templates/orden/orden_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static "orden/css/orden-list.css" %}">
{% endblock stylesheets %}

{% block content %}
<div class="ordenes">
    <h1>Ordenes</h1>
    <table class="ordenes-tabla">
        <tr>
            <th>Nombre del cliente</th>
            <th>Vehiculo</th>
            <th>Patente</th>
            <th>Telefono</th>
            <th>Cobertura</th>
            <th>Siguiente paso</th>
        </tr>
        {% for orden in ordenes %}
        <tr>
            <td><a href='{% url 'orden:detail' id=orden.id %}'>{{orden.nombre_cliente}}</a></td>
            <td>{{orden.marca_vehiculo}} {{orden.modelo_vehiculo}}</td>
            <td>{{orden.patente_vehiculo}}</td>
            <td>{{orden.telefono_cliente}}</td>
            <td>{{orden.get_modalidad_display}}</td>
            <td class='estado-vehiculo'>{{ orden.get_estado_display }}</td>
        </tr>
        {% empty %}
        <li>No Ordenes yet.</li>
        {% endfor %}
    </table>
    <h2><a href="{% url "orden:create" %}">Agregar Orden</a></h2>
</div>
{% endblock content %}